import { useEffect, useState } from "react";
import { api } from "../api/client";
import type { HospitalConfig } from "../api/types";

const defaults: HospitalConfig = { arrivalsPerHour: 25, doctors: 5, nurses: 8, beds: 20, triageNurses: 2, ctCapacity: 1, labCapacity: 2, minutesPerPatientDoctor: 11, severityMix: { critical: .12, serious: .38, mild: .50 } };

export default function Config() {
  const [config, setConfig] = useState<HospitalConfig>(defaults); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api.getConfig().then(setConfig).catch((e) => setError(e.message)); }, []);
  const set = (key: keyof HospitalConfig, value: number) => setConfig((c) => ({ ...c, [key]: value }));
  const setMix = (key: keyof HospitalConfig["severityMix"], value: number) => setConfig((c) => ({ ...c, severityMix: { ...c.severityMix, [key]: value } }));
  const save = async () => { setSaving(true); setMessage(""); setError(""); try { const result = await api.updateConfig(config); setConfig(result); setMessage("Configuration saved. Command Center calculations now use this baseline."); } catch (e) { setError(e instanceof Error ? e.message : "Could not save configuration"); } finally { setSaving(false); } };
  const mixTotal = config.severityMix.critical + config.severityMix.serious + config.severityMix.mild;
  return <div><header className="page-header dashboard-header"><div><div className="eyebrow">HOSPITAL SETUP</div><h1>Ward configuration</h1><p>Set the operational baseline used by PulseTwin status, scenarios, and recommendations.</p></div><button className="btn-primary" disabled={saving} onClick={save}>{saving ? "Saving…" : "Save baseline"}</button></header>{message && <div className="config-message success">✓ {message}</div>}{error && <div className="config-message error">{error}</div>}<div className="config-grid"><section className="card"><div className="section-heading"><div><div className="eyebrow">CAPACITY & STAFFING</div><h2>Available resources</h2></div><span className="status-pill healthy">LIVE BASELINE</span></div><div className="form-grid">{([ ["arrivalsPerHour","Arrivals / hour","Expected ED arrivals per hour"],["doctors","Doctors","On-shift physicians"],["nurses","Nurses","On-shift nursing staff"],["beds","Beds","Staffed treatment beds"],["triageNurses","Triage nurses","Front-door triage capacity"],["ctCapacity","CT capacity","Concurrent CT slots"],["labCapacity","Lab capacity","Concurrent lab slots"],["minutesPerPatientDoctor","Doctor minutes / patient","Mean physician service time"]] as [keyof HospitalConfig,string,string][]).map(([key,label,help]) => <label className="config-field" key={key}><span>{label}<small>{help}</small></span><input type="number" min="0" step={key === "minutesPerPatientDoctor" ? .5 : 1} value={config[key] as number} onChange={(e) => set(key, Number(e.target.value))}/></label>)}</div></section><section className="card"><div className="section-heading"><div><div className="eyebrow">PATIENT MIX</div><h2>Arrival acuity</h2></div><span className={`status-pill ${Math.abs(mixTotal-1)<.01 ? "healthy" : "warning"}`}>{Math.round(mixTotal*100)}% TOTAL</span></div><p className="config-copy">Adjust the baseline share of arrivals by severity. The mix must equal 100% before saving.</p>{([ ["critical","Critical","Immediate attention"],["serious","Serious","Priority treatment"],["mild","Mild","Standard flow"]] as [keyof HospitalConfig["severityMix"],string,string][]).map(([key,label,help]) => <label className="mix-field" key={key}><span><b>{label}</b><small>{help}</small></span><input type="range" min="0" max="1" step=".01" value={config.severityMix[key]} onChange={(e) => setMix(key, Number(e.target.value))}/><strong>{Math.round(config.severityMix[key]*100)}%</strong></label>)}<div className="mix-bar"><span className="critical" style={{width:`${config.severityMix.critical*100}%`}}/><span className="serious" style={{width:`${config.severityMix.serious*100}%`}}/><span className="mild" style={{width:`${config.severityMix.mild*100}%`}}/></div><div className="config-note">Changes are persisted to the configured database. With <code>DATABASE_URL</code>, PulseTwin uses PostgreSQL; without it, local development uses SQLite.</div></section></div></div>;
}
