import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api, ApiError } from "../api/client";
import type { EvaluationResult, ParsedScenario } from "../api/types";

export default function Recommendation({ scenario, onSelectCandidate }: { scenario: ParsedScenario | null; onSelectCandidate: (scenarioId: string, candidateId: string) => void; }) {
  const [result, setResult] = useState<EvaluationResult | null>(null); const [status, setStatus] = useState("loading"); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false); const navigate = useNavigate();
  const run = () => { if (!scenario) return; setStatus("loading"); setError(null); api.evaluateScenario(scenario).then(r=>{setResult(r);setStatus("ready");}).catch((e:ApiError)=>{setError(e.message);setStatus("error");}); };
  useEffect(run, [scenario]);
  if (!scenario) return <div><PageHeader/><div className="empty-state"><h2>No scenario yet</h2><p>Start with a question to run the twin.</p><button className="btn-primary" onClick={()=>navigate("/ask")}>Ask a question →</button></div></div>;
  return <div><PageHeader question={scenario.rawQuestion}/>{status === "loading" && <div className="loading-pipeline"><div className="spinner"/><div><strong>Running the decision engine</strong><p>Screening configurations → validating with simulation → scoring patient impact</p></div></div>}{status === "error" && <div className="state-error">{error}<div><button className="btn-ghost" onClick={run}>Retry</button></div></div>}{result && <>
    <div className="pipeline"><span className="done">01 Question parsed</span><span className="done">02 Fast screen</span><span className="done">03 DES validation</span><span className="done">04 Optimize</span><span className="active">05 Explain</span></div>
    <section className="recommendation-hero"><div><div className="eyebrow">RECOMMENDATION · SEVERITY-AWARE</div><h2>{result.recommendation.summary}</h2><p>{result.recommendation.reasoning}</p><div className="hero-meta"><span>⌁ {result.recommendation.whyNow}</span><span className="status-pill healthy">SIMULATED · {new Date(result.computedAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div></div><div className="impact-grid"><Impact label="Avg wait" value={result.recommendation.impact.avgWaitReduction} unit="min"/><Impact label="Critical wait" value={result.recommendation.impact.criticalWaitReduction} unit="min"/><Impact label="Throughput" value={result.recommendation.impact.throughputGain} unit="/hr"/></div></section>
    <div className="section-heading compare-heading"><div><div className="eyebrow">CANDIDATE COMPARISON</div><h2>Fast screen → detailed simulation</h2></div><span className="mono">{result.candidates.length} validated candidates</span></div>
    <div className="candidate-table"><div className="candidate-head"><span>Configuration</span><span>Avg wait</span><span>Critical wait</span><span>Doctor load</span><span>Score</span><span/></div>{[result.baseline,...result.candidates].map(c=><div className={`candidate-row ${c.isRecommended?"recommended":""}`} key={c.id}><div><strong>{c.label}</strong>{c.isRecommended&&<span className="recommended-tag">BEST TRADE-OFF</span>}<small>{c.tradeoff}</small></div><span className="mono">{c.avgWaitMinutes} <em>min</em></span><span className="mono critical-number">{c.criticalWaitMinutes} <em>min</em></span><div className="inline-meter"><span style={{width:`${Math.min(100,c.doctorUtilizationPct)}%`}}/><small>{c.doctorUtilizationPct}%</small></div><span className="mono score-number">{c.score}</span><button className={c.isRecommended?"btn-primary":"btn-ghost"} onClick={()=>{onSelectCandidate(scenario.id,c.id);navigate("/ward");}}>{c.isRecommended?"Open twin →":"View"}</button></div>)}</div>
    <div className="bottom-grid"><div className="card"><div className="eyebrow">WHY THIS DECISION</div><h3>Traceable, not magical</h3><p className="decision-copy">The optimizer weights overall wait, critical-patient wait, utilization, and staffing cost. Queueing mathematics narrowed the search; the discrete-event simulation validated the strongest options.</p><div className="guardrails">{result.recommendation.guardrails.map(g=><div key={g}>✓ {g}</div>)}</div></div><div className="card save-card"><div className="eyebrow">DECISION RECORD</div><h3>Keep this scenario</h3><p>Store the recommendation so your team can compare decisions during the shift.</p><button className="btn-primary" disabled={saved} onClick={()=>api.createDecision({scenarioId:scenario.id,question:scenario.rawQuestion,recommendation:result.recommendation.summary,impact:result.recommendation.impact}).then(()=>setSaved(true))}>{saved?"✓ Saved to history":"Save decision"}</button><button className="btn-ghost" onClick={()=>navigate("/history")}>View history →</button></div></div>
  </>}</div>;
}
function Impact({label,value,unit}:{label:string;value:number;unit:string}) { return <div className="impact-card"><small>{label} reduction</small><strong>{value > 0 ? "−" : "+"}{Math.abs(value)}<em>{unit}</em></strong><span>vs current staffing</span></div>; }
function PageHeader({question}:{question?:string}) { return <header className="page-header"><div className="eyebrow">DECISION ENGINE / SCREEN → SIMULATE → OPTIMIZE</div><h1>Twin Optimizer</h1>{question&&<p>For: <span className="quoted">“{question}”</span></p>}</header>; }
